# Use the official Postgres image as the base image
FROM postgis/postgis:latest

# Set environment variables for Postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD admin123
ENV POSTGRES_DB isro_postgis

# Expose the default PostgreSQL port
EXPOSE 5432

# Build and run the Docker container
# docker build -t my-postgis-container .
# docker run -p 5432:5432 --name my-postgis-container my-postgis-container

